version: "3"
services:
  pixelflut-server:
    image: docker.io/sbernauer/breakwater:0.12.0
    entrypoint: [ "breakwater", "-l", "[::]:1234", "--vnc-port", "5900" ]
    command: --width 1280 --height 720 --text "Hacktoberfest 2023 - Crazy Canvas"
    # If you are on linux, disable the network_mode line and remove the ports to make things go whuuuuusch
    #network_mode: host
    ports:
      - 1234:1234
      - 5900:5900

  vnc2html:
    image: ghcr.io/poeschl/vnc2html
    # If you are on linux, disable the network_mode line and remove the ports to make things go whuuuuusch
    #network_mode: host
    ports:
      - 8088:8080
    environment:
      VNC_HOST: pixelflut-server
      VNC_PORT: 5900
      PLAYER_ROOT: http://localhost:8088
      TITLE: "Hacktoberfest 2023"
